Close store if created in RenderedImageServer
qupath/qupath pull request #1577
Opened 2024-08-07 14:55 UTC by Rylern

A proposal to fix #1561.

With this PR, a `RenderedImageServer` will close its underlying `DefaultImageRegionStore` if this store was created within the `RenderedImageServer` class.

2024-08-07 16:26 UTC, petebankhead commented
Thanks, I made minor edits to ensure `super.close()` is called as well, and made some variables final.

One worry, possibly obscure: it looks like `dedicatedStore` is being set as a side-effect or calling `getStore()`.

That's fine if the builder is only used once, but if it is reused and passed a different `store` (or `findViewer()` gives a non-null result) before the second use then I think we could still end up closing a store that is being used elsewhere.

Possible workarounds:
1. Move the `getStore()` logic into `build()` so that `dedicatedStore` doesn't need to be a field of the builder
2. Reset the value of `dedicatedStore` whenever its value may change (e.g. `findViewer(imageData)` doesn't return `null`, or `store` is updated)
3. Build the store inside the `RenderedImageServer` if the store it is given is `null` - and then set `dedicatedStore` only within `RenderedImageServer` (which knows whether or not it created a store)

I tend to think Option 3. might be the easiest to code, and most robust.

2024-08-07 16:33 UTC, petebankhead requested changes
Changes requested as described above (ensuring the builder can be reused safely).

2024-08-08 08:49 UTC, Rylern commented
I implemented option 3

2024-08-08 11:04 UTC, petebankhead approved these changes

2024-08-08 11:05 UTC, merged